### ISSUE TITLE
dotgit generate ignores "subtle" changes in filelist

### ISSUE THREAD

**Issue by lamarpavel** [Cube777/dotgit#10]
When editing the filelist in a way that does not cause the repo to change (eg. only adding a comment) then `dotgit generate` aborts with message *No changes to repository* and the modified filelist ist not commited and pushed to remote.

Right now, such changes have to be manually commited and pushed (eg `git add filelist && git commit -m "modifiy filelist" && git push`). Is this behaviour intended?

**Comment by Cube777** [comment]
The behaviour is not really intended but not unexpected - it always excludes the filelist when it does an internal diff. I'll add an exception for when the filelist is the only changed file :+1:

**Comment by lamarpavel** [comment]
Nice, thank you for the quick response.
