### ISSUE TITLE
handle spaces in filenames

### ISSUE THREAD

**Issue by ashkitten** [Cube777/dotgit#3]

**Comment by Cube777** [comment]
Thanks for pointing this out - I'm currently restructuring the code base with the goal of fixing this and #2 (see branch split). I'm currently very busy with university but I will work on this as often as possible :+1:

**Comment by Cube777** [comment]
Hey @ashkitten  , I finally got around to rewriting dotgit and spaces inside filenames should now be handled correctly. Please have a look at [this post](https://bbs.archlinux.org/viewtopic.php?pid=1720722#p1720722) for instructions. Have a good day!

**Comment by Cube777** [comment]
Fixed in 1.4.1
