### ISSUE TITLE
Missing syntax definition for optional categories

### ISSUE THREAD

**Issue by lamarpavel** [Cube777/dotgit#6]
Hey,
I've been trying out dotgit and it's working really well. I only have a minor nitpick about the docs so far.

In the documentation section `OPTIONS` we are lacking the syntax definition for the `(args)`. In a previous section the syntax for adding `categories` in the filelist is described as comma separated and without spaces: eg. `.vimrc:editor,coding`.
Due to lack of definition I tried this same syntax as argument: eg `dotgit update editor,coding`, which turned out to be wrong.

Please add one sentence or an example to describe the syntax, such as:
```
[...] Options with "(args)" after their name support categories as a space separated list.
```

And while we're on the subject, you can just replace *args* with *categories*. The substitution isn't needed as long as the only possible *args* are *categories*.

Thanks for developing this tool.

**Comment by Cube777** [comment]
Hey @lamarpavel, thank you for pointing out the problem inside the docs I will fix the issue asap

**Comment by lamarpavel** [comment]
Thanks for the quick response.

Maybe you should also add a hint that doing `dotgit update` will remove all files from your home directory that are listed in the filelist, but are not associated with your hostname or *common*. If someone wants to add **.xinitrc** and only associate it with the category *gui* (`.xinitrc:gui`) then `dotgit update gui` will remove the file and **not** replace it with a link.

As a user coming from vcsh I intuitively categorised everything and thought "I'll check out gui on my desktop and laptop". Reading the documentation carefully will make clear that files can "vanish" after you add them and do `dotgit update`, but maybe a warning or hint that you may have to do a `dotgit restore` afterwards should be added.

**Comment by Cube777** [comment]
I updated the docs to reflect your recommendations, thank you for pointing it out. As for the issue you mentioned regarding the update not creating a link to the home folder I was unable to replicate the bug. If you could maybe file a new issue with more details (verbose output and maybe a link to your repo) I would gladly take a look :)
