### ISSUE TITLE
Feature: category composition / hostname alias

### ISSUE THREAD

**Issue by lamarpavel** [Cube777/dotgit#7]
Let me start by saying that this is more of an idea I want to discuss and less of a feature request since I'm not entirely sure what the best way would be to implement this (or if the same could be achieved differently).

What I would like to do is define a *group* as composition of categories and then use this defined *group* in the `filelist`. Example filelist:

```
# defined groups
mygroupA=coding,work,gui,zsh
mygroupB=srv,zsh

.zshrc:zsh
.zprofile:zsh
.zlogout:zsh
.ssh/authorized_keys:srv
.vimrc:coding
.xinitrc:gui
[...]
```

Now, when doing `dotgit update` (or `dotgit restore`) and I pass *mygroupA*, it would be subsituted to `dotgit update coding work gui zsh`. There are several reasons why I think it's useful:

- If I want to replace zsh with bash on a server where I check out *mygroupB*, I only have to change one line where *mygroupB* is defined instead of multiple lines where zsh-files are listed (if I were to associate them with real hostnames)
- On some systems I am maintaining several users that all share the same hostname but not the same use cases, such that I don't want to check out the same files for them
- I could achieve the same by having a shell alias like `dotgitUpdateA='dotgit update coding work gui zsh'` and `dotgitUpdateB='dotgit update srv zsh'` (and the same for restore), but then I would spam my bashrc/zshrc with new lines that most users don't need and it's not very nice for config hygene because some of the config for dotgit is now in my shells config file etc

Something I am not sure about is re-defining a hostname in this way. It would be even more convenient to just write `dotgit update` on a host named *hostA* and define `hostA=coding,work.gui,zsh` for implicit substitution on that machine. But what about `common` in that case? Could this lead to unexpected behaviour?

In the end it's just syntax sugar for convenience. But then again, convenience is why we use tools like dotgit, isn't it?

Cheers

**Comment by Cube777** [comment]
Hi @lamarpavel ,

Thank you for the idea - this seems like a great feature to add. Will get on this asap.

Cheers

**Comment by Cube777** [comment]
I implemented it the same way you described in your comment ("group=category1,category2") inside any of the two filelists. I would appreciate it if you can check that it works for you as you'd like (verbose mode will show you how it expands the groups) :) Bash completion also works for categories. I'll add documentation and release a new version as soon as the syntax is finalized and tested :+1:

**Comment by lamarpavel** [comment]
Great, thanks for the quick response. I'll test it and report back.

**Comment by Cube777** [comment]
When dotgit implicitly adds the hostname/common it will also check to see if it matches a group (as specified in the second to last paragraph of your first comment). So if you have a host named "groupA" and a group defined as "groupA=cat1,cat2" and you run `dotgit update` (no categories specified) it will use cat1,cat2 (expanded from groupA as hostname) and common.

**Comment by lamarpavel** [comment]
Brilliant timing, I was just modifying my filelist and wondering about that exact issue. Came here to ask before doing a `dotgit update`.

**Comment by lamarpavel** [comment]
Seems to work fine. I also tested a corner case; my hostname being *laptop* I added `laptop=laptop` to the top of `filelist` and left my files defined as `.zshrc:desktop,laptop` etc, and it works well. This makes testing the group feature especially easy.

Anything else you want me to test?

**Comment by Cube777** [comment]
Glad to hear everything works as expected :) Will update the docs and release a new version, thanks again for the idea :+1:

**Comment by lamarpavel** [comment]
Great, and thank *you* for implementing it :+1:
